// Catálogo curado de exercícios (005 / T-001). Linhas GLOBAIS (owner_user_id null).
// ≥ 40 exercícios cobrindo push / pull / pernas / core + isométricos de skill.
//
// Convenções (R7 — padronizar slugs):
//  • slug em kebab-case, estável e único. É a chave de idempotência do seed.
//  • cues: 1 frase curta de forma/segurança (RNF-001). SEMPRE preenchido.
//  • isSkill + defaultUnit 'seconds' nos isométricos (medem max-hold).
//  • demoUrl: null em v1 (RNF-002) — curadoria de mídia é portão humano.
//
// As escadas (skills.ts) referenciam estes slugs via SeedSkillLevel.exerciseSlug.
// Ao adicionar/remover, rode `npm run verify:content` (validação offline).

import type { SeedExercise } from "./types.ts";

export const EXERCISES: SeedExercise[] = [
  // ── PUSH (empurrar) ────────────────────────────────────────────────
  {
    slug: "push-up",
    name: "Flexão de braço",
    category: "forca",
    pattern: "push",
    equipment: ["floor"],
    cues: "Corpo em linha (hollow leve), cotovelos ~45°, peito quase ao chão.",
    demoUrl: null,
  },
  {
    slug: "knee-push-up",
    name: "Flexão com joelhos no chão",
    category: "forca",
    pattern: "push",
    equipment: ["floor"],
    cues: "Regressão da flexão: quadril alinhado com o tronco, sem empinar.",
    demoUrl: null,
  },
  {
    slug: "incline-push-up",
    name: "Flexão inclinada (mãos elevadas)",
    category: "forca",
    pattern: "push",
    equipment: ["floor", "bench"],
    cues: "Quanto mais alta a superfície, mais fácil. Mantém a linha do corpo.",
    demoUrl: null,
  },
  {
    slug: "diamond-push-up",
    name: "Flexão diamante (tríceps)",
    category: "forca",
    pattern: "push",
    equipment: ["floor"],
    cues: "Mãos juntas sob o peito, cotovelos rentes ao corpo.",
    demoUrl: null,
  },
  {
    slug: "pseudo-planche-push-up",
    name: "Pseudo planche push-up (PPPU)",
    category: "forca",
    pattern: "push",
    equipment: ["floor", "parallettes"],
    cues: "Ombros à frente das mãos, protrai as escápulas, lean progressivo.",
    demoUrl: null,
  },
  {
    slug: "pike-push-up",
    name: "Pike push-up",
    category: "forca",
    pattern: "push",
    equipment: ["floor"],
    cues: "Quadril alto (V invertido), cabeça desce entre as mãos.",
    demoUrl: null,
  },
  {
    slug: "dip",
    name: "Mergulho (dip) em paralelas",
    category: "forca",
    pattern: "push",
    equipment: ["dip-bar", "parallettes"],
    cues: "Desce controlado até ombro na linha do cotovelo, sem encolher o pescoço.",
    demoUrl: null,
  },
  {
    slug: "bench-dip",
    name: "Mergulho no banco",
    category: "forca",
    pattern: "push",
    equipment: ["bench"],
    cues: "Regressão do dip: cotovelos para trás, ombros longe das orelhas.",
    demoUrl: null,
  },
  {
    slug: "wall-handstand-push-up",
    name: "HSPU na parede",
    category: "forca",
    pattern: "push",
    equipment: ["wall", "floor"],
    cues: "Cabeça desce em triângulo com as mãos; corpo alinhado, sem arquear.",
    demoUrl: null,
  },

  // ── PULL (puxar) ────────────────────────────────────────────────────
  {
    slug: "pull-up",
    name: "Barra fixa (pull-up)",
    category: "forca",
    pattern: "pull",
    equipment: ["bar"],
    cues: "Inicia com retração escapular, queixo passa a barra, descida controlada.",
    demoUrl: null,
  },
  {
    slug: "chin-up",
    name: "Barra supinada (chin-up)",
    category: "forca",
    pattern: "pull",
    equipment: ["bar"],
    cues: "Pegada supinada na largura dos ombros; bom para bíceps/cotovelo.",
    demoUrl: null,
  },
  {
    slug: "negative-pull-up",
    name: "Negativa de barra",
    category: "forca",
    pattern: "pull",
    equipment: ["bar"],
    cues: "Sobe assistido, desce 3-5s controlado. Regressão para 1ª barra.",
    demoUrl: null,
  },
  {
    slug: "australian-row",
    name: "Remada australiana (inverted row)",
    category: "forca",
    pattern: "pull",
    equipment: ["bar", "rings"],
    cues: "Corpo reto, puxa o peito à barra, escápulas retraídas no topo.",
    demoUrl: null,
  },
  {
    slug: "scapular-pull",
    name: "Scap pulls (ativação escapular)",
    category: "forca",
    pattern: "pull",
    equipment: ["bar"],
    cues: "Pendurado, deprime/retrai as escápulas sem dobrar o cotovelo.",
    demoUrl: null,
  },
  {
    slug: "tuck-front-lever-row",
    name: "Tuck front lever row",
    category: "forca",
    pattern: "pull",
    equipment: ["bar"],
    cues: "Puxada horizontal específica de FL; mantém quadril alto na linha.",
    demoUrl: null,
  },
  {
    slug: "bodyweight-curl",
    name: "Curl de corpo na barra",
    category: "forca",
    pattern: "pull",
    equipment: ["bar"],
    cues: "Saúde do cotovelo: flexão de cotovelo controlada, sem balanço.",
    demoUrl: null,
  },
  {
    slug: "dead-hang",
    name: "Pendurada passiva (dead hang)",
    category: "forca",
    pattern: "pull",
    isSkill: false,
    defaultUnit: "seconds",
    equipment: ["bar"],
    cues: "Pegada firme, ombros ativos; constrói grip e saúde de ombro.",
    demoUrl: null,
  },

  // ── PERNAS ──────────────────────────────────────────────────────────
  {
    slug: "bodyweight-squat",
    name: "Agachamento livre",
    category: "pernas",
    pattern: "legs",
    equipment: ["floor"],
    cues: "Joelhos seguem a ponta dos pés, profundidade confortável, tronco firme.",
    demoUrl: null,
  },
  {
    slug: "split-squat",
    name: "Agachamento búlgaro / split squat",
    category: "pernas",
    pattern: "legs",
    equipment: ["floor", "bench"],
    cues: "Passada longa, joelho de trás desce reto, peso no calcanhar da frente.",
    demoUrl: null,
  },
  {
    slug: "assisted-pistol-squat",
    name: "Pistol assistido",
    category: "pernas",
    pattern: "pistol",
    equipment: ["floor", "band"],
    cues: "Segure um apoio leve; desça controlado numa perna, calcanhar no chão.",
    demoUrl: null,
  },
  {
    slug: "box-pistol-squat",
    name: "Pistol no caixote (parcial)",
    category: "pernas",
    pattern: "pistol",
    equipment: ["floor", "bench"],
    cues: "Senta num apoio e sobe numa perna; baixe a altura ao progredir.",
    demoUrl: null,
  },
  {
    slug: "pistol-squat",
    name: "Pistol squat (completo)",
    category: "pernas",
    pattern: "pistol",
    isSkill: true,
    equipment: ["floor"],
    cues: "Agachamento numa perna até o fim, perna livre estendida à frente, sem colapso do joelho.",
    demoUrl: null,
  },
  {
    slug: "nordic-curl",
    name: "Nórdico (nordic hamstring)",
    category: "pernas",
    pattern: "legs",
    equipment: ["floor"],
    cues: "Desça os mais lento possível resistindo; progressão conservadora (joelho).",
    demoUrl: null,
  },
  {
    slug: "glute-bridge",
    name: "Ponte de glúteo",
    category: "pernas",
    pattern: "legs",
    equipment: ["floor"],
    cues: "Empurra pelos calcanhares, contrai o glúteo no topo sem hiperestender a lombar.",
    demoUrl: null,
  },
  {
    slug: "hip-thrust-single-leg",
    name: "Hip thrust unilateral",
    category: "pernas",
    pattern: "legs",
    equipment: ["floor", "bench"],
    cues: "Quadril sobe numa perna; coluna neutra, glúteo faz o trabalho.",
    demoUrl: null,
  },
  {
    slug: "calf-raise",
    name: "Elevação de panturrilha",
    category: "pernas",
    pattern: "legs",
    equipment: ["floor"],
    cues: "Amplitude total, pausa no topo, descida controlada.",
    demoUrl: null,
  },
  {
    slug: "wall-sit",
    name: "Cadeira na parede (wall sit)",
    category: "pernas",
    pattern: "legs",
    defaultUnit: "seconds",
    equipment: ["wall"],
    cues: "Coxas paralelas ao chão, costas na parede, respiração estável.",
    demoUrl: null,
  },

  // ── CORE ────────────────────────────────────────────────────────────
  {
    slug: "hollow-body-hold",
    name: "Hollow body hold",
    category: "core",
    pattern: "core",
    defaultUnit: "seconds",
    equipment: ["floor"],
    cues: "Lombar colada ao chão (leve retroversão), sem hiperextensão.",
    demoUrl: null,
  },
  {
    slug: "plank",
    name: "Prancha frontal",
    category: "core",
    pattern: "core",
    defaultUnit: "seconds",
    equipment: ["floor"],
    cues: "Linha ombro-quadril-tornozelo, glúteo e abdômen ativos, sem cair o quadril.",
    demoUrl: null,
  },
  {
    slug: "side-plank",
    name: "Prancha lateral",
    category: "core",
    pattern: "core",
    defaultUnit: "seconds",
    equipment: ["floor"],
    cues: "Quadril elevado, corpo numa linha; anti-flexão lateral (McGill).",
    demoUrl: null,
  },
  {
    slug: "bird-dog",
    name: "Bird dog",
    category: "core",
    pattern: "core",
    equipment: ["floor"],
    cues: "Estende braço/perna opostos mantendo a coluna neutra e o quadril nivelado.",
    demoUrl: null,
  },
  {
    slug: "dead-bug",
    name: "Dead bug",
    category: "core",
    pattern: "core",
    equipment: ["floor"],
    cues: "Lombar no chão o tempo todo; baixa braço/perna opostos sem arquear.",
    demoUrl: null,
  },
  {
    slug: "mcgill-curl-up",
    name: "McGill curl-up",
    category: "core",
    pattern: "core",
    equipment: ["floor"],
    cues: "Uma perna dobrada, mãos sob a lombar; eleva só cabeça/ombros, coluna neutra.",
    demoUrl: null,
  },
  {
    slug: "hanging-knee-raise",
    name: "Elevação de joelhos suspenso",
    category: "core",
    pattern: "core",
    equipment: ["bar"],
    cues: "Controlado, sem balanço/kipping; retroverte a pelve para subir.",
    demoUrl: null,
  },
  {
    slug: "hanging-leg-raise",
    name: "Elevação de pernas suspenso",
    category: "core",
    pattern: "core",
    equipment: ["bar"],
    cues: "Pernas estendidas, sobe sem impulso; progressão da elevação de joelhos.",
    demoUrl: null,
  },
  {
    slug: "l-sit",
    name: "L-sit",
    category: "core",
    pattern: "core",
    isSkill: true,
    defaultUnit: "seconds",
    equipment: ["parallettes", "floor"],
    cues: "Pernas estendidas à frente, ombros deprimidos, compressão ativa do core.",
    demoUrl: null,
  },

  // ── ISOMÉTRICOS DE SKILL — Front Lever ──────────────────────────────
  {
    slug: "tuck-front-lever",
    name: "Front lever — tuck",
    category: "skill",
    pattern: "front",
    isSkill: true,
    defaultUnit: "seconds",
    equipment: ["bar", "rings"],
    cues: "Joelhos ao peito, escápulas deprimidas/retraídas, costas paralelas ao chão.",
    demoUrl: null,
  },
  {
    slug: "advanced-tuck-front-lever",
    name: "Front lever — advanced tuck",
    category: "skill",
    pattern: "front",
    isSkill: true,
    defaultUnit: "seconds",
    equipment: ["bar", "rings"],
    cues: "Abre o ângulo do quadril mantendo a lombar neutra e o tronco horizontal.",
    demoUrl: null,
  },
  {
    slug: "straddle-front-lever",
    name: "Front lever — straddle / one-leg",
    category: "skill",
    pattern: "front",
    isSkill: true,
    defaultUnit: "seconds",
    equipment: ["bar", "rings"],
    cues: "Pernas afastadas (ou uma estendida) reduzem a alavanca; corpo na horizontal.",
    demoUrl: null,
  },
  {
    slug: "full-front-lever",
    name: "Front lever — completo",
    category: "skill",
    pattern: "front",
    isSkill: true,
    defaultUnit: "seconds",
    equipment: ["bar", "rings"],
    cues: "Corpo todo na horizontal, hollow ativo; nunca force além do hold limpo.",
    demoUrl: null,
  },
  {
    slug: "front-lever-negative",
    name: "Front lever — negativa",
    category: "skill",
    pattern: "front",
    isSkill: true,
    defaultUnit: "seconds",
    equipment: ["bar"],
    cues: "Desce 4-5s do inverted hang/tuck até a horizontal, controlando a posição.",
    demoUrl: null,
  },

  // ── ISOMÉTRICOS DE SKILL — Planche ──────────────────────────────────
  {
    slug: "planche-lean",
    name: "Planche lean",
    category: "skill",
    pattern: "planche",
    isSkill: true,
    defaultUnit: "seconds",
    equipment: ["floor", "parallettes"],
    cues: "Ombros bem à frente das mãos, escápulas protraídas; condiciona punho/cotovelo.",
    demoUrl: null,
  },
  {
    slug: "tuck-planche",
    name: "Planche — tuck",
    category: "skill",
    pattern: "planche",
    isSkill: true,
    defaultUnit: "seconds",
    equipment: ["floor", "parallettes"],
    cues: "Joelhos ao peito, quadril acima da linha dos ombros, protração total.",
    demoUrl: null,
  },
  {
    slug: "advanced-tuck-planche",
    name: "Planche — advanced tuck",
    category: "skill",
    pattern: "planche",
    isSkill: true,
    defaultUnit: "seconds",
    equipment: ["floor", "parallettes"],
    cues: "Costas arredondadas abrindo o quadril; mantém protração e punho aquecido.",
    demoUrl: null,
  },
  {
    slug: "straddle-planche",
    name: "Planche — straddle",
    category: "skill",
    pattern: "planche",
    isSkill: true,
    defaultUnit: "seconds",
    equipment: ["floor", "parallettes"],
    cues: "Pernas afastadas e estendidas; corpo paralelo ao chão, lean firme.",
    demoUrl: null,
  },
  {
    slug: "full-planche",
    name: "Planche — completo",
    category: "skill",
    pattern: "planche",
    isSkill: true,
    defaultUnit: "seconds",
    equipment: ["floor", "parallettes"],
    cues: "Corpo reto e horizontal sobre as mãos; progressão lenta para poupar o cotovelo.",
    demoUrl: null,
  },

  // ── ISOMÉTRICOS DE SKILL — Parada de mão (handstand) ────────────────
  {
    slug: "wall-plank-hold",
    name: "Wall plank / hollow hold de parede",
    category: "skill",
    pattern: "handstand",
    isSkill: true,
    defaultUnit: "seconds",
    equipment: ["wall", "floor"],
    cues: "Prancha alta com pés na parede; trabalha alinhamento e ombro de HS.",
    demoUrl: null,
  },
  {
    slug: "chest-to-wall-handstand",
    name: "Parada de mão peito-à-parede",
    category: "skill",
    pattern: "handstand",
    isSkill: true,
    defaultUnit: "seconds",
    equipment: ["wall", "floor"],
    cues: "Barriga para a parede, corpo alinhado e empilhado, ombros elevados.",
    demoUrl: null,
  },
  {
    slug: "back-to-wall-handstand",
    name: "Parada de mão costas-à-parede",
    category: "skill",
    pattern: "handstand",
    isSkill: true,
    defaultUnit: "seconds",
    equipment: ["wall", "floor"],
    cues: "Sobe de chute leve, busca a linha; sai com segurança rolando ou pisando.",
    demoUrl: null,
  },
  {
    slug: "freestanding-handstand",
    name: "Parada de mão livre",
    category: "skill",
    pattern: "handstand",
    isSkill: true,
    defaultUnit: "seconds",
    equipment: ["floor"],
    cues: "Equilíbrio pelos dedos, corpo empilhado; sempre tenha saída de segurança.",
    demoUrl: null,
  },

  // ── ISOMÉTRICOS/PROGRESSÃO — Muscle-up ──────────────────────────────
  {
    slug: "high-pull-up",
    name: "Pull-up alto (explosivo)",
    category: "forca",
    pattern: "muscle-up",
    equipment: ["bar"],
    cues: "Puxa explosivo trazendo o peito acima da barra; base de potência do MU.",
    demoUrl: null,
  },
  {
    slug: "straight-bar-dip",
    name: "Dip na barra reta",
    category: "forca",
    pattern: "muscle-up",
    equipment: ["bar"],
    cues: "Apoiado acima da barra, desce e sobe controlado; treina a fase de transição.",
    demoUrl: null,
  },
  {
    slug: "muscle-up-transition-negative",
    name: "Negativa de transição do muscle-up",
    category: "skill",
    pattern: "muscle-up",
    isSkill: true,
    defaultUnit: "seconds",
    equipment: ["bar", "rings"],
    cues: "Desce lento da posição de apoio passando a transição; ensina o caminho.",
    demoUrl: null,
  },
  {
    slug: "muscle-up",
    name: "Muscle-up",
    category: "skill",
    pattern: "muscle-up",
    isSkill: true,
    equipment: ["bar", "rings"],
    cues: "Puxa alto, transição rápida do punho, finaliza no dip; sem kipping agressivo no início.",
    demoUrl: null,
  },
];
